version: '3.7'
services:
  app:
    image: php:8-alpine
    working_dir: /var/www/html
    command: php -S 0.0.0.0:8080 -t public
    environment:
      docker: "true"
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    container_name: auth-app
  db:
    image: mysql:latest
    env_file:
      - ./.env
    ports:
      - "13306:3306"
    container_name: auth-db
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: